name: Backend Quality & Security

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. Calidad de Código (Linting)
      - name: Lint with Flake8
        run: |
          pip install flake8
          # Detiene la ejecución si hay errores de sintaxis o variables no definidas
          flake8 ./backend --count --select=E9,F63,F7,F82 --show-source --statistics

      # 2. Seguridad del Código (SAST)
      - name: Security scan with Bandit
        run: |
          pip install bandit
          bandit -r ./backend/app -ll

      # 3. Construcción de la Imagen (Check de Build)
      - name: Build Docker Image
        run: |
          docker build -t pro-app:${{ github.sha }} ./backend

      # 4. Escaneo de Vulnerabilidades en la Imagen (Trivy)
      - name: Container Image Scan (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'pro-app:${{ github.sha }}'
          format: 'table'
          exit-code: '1' # El pipeline falla si encuentra algo CRÍTICO
          ignore-unfixed: true
          severity: 'CRITICAL'